### ISSUE TITLE
[1.1.1] HTTP Error: HTTP GET error on '/?encoding-type=url&list-type=2&prefix=' (HTTP 400)

### ISSUE THREAD

**Issue by qw-in** [tobilg/duckdb-nodejs-layer#12]
Hey, sorry just at a bit of a loss with this one. Opening here as I can't reproduce with the npm version of `duckdb-node`. Hoping you could point me in the right direction - my brain is melting

---

Anyway, updating to the `1.1.X` version of this layer (`x86_64` & `arm64`) I see a `400` error when attempting to read from an `r2` bucket. This error does not occur on `1.0.0` of the layer.

I can also not reproduce the issue in the `cli` locally, or running via `duckdb-node` locally (both macOS arm64)

---

To reproduce, it's essentially this:

```
SET home_directory='/tmp';
SET temp_directory='/tmp/.tmp';
SET custom_extension_repository = 'http://extensions.quacking.cloud';
INSTALL httpfs;
LOAD httpfs;
SET enable_http_metadata_cache=true;
SET enable_object_cache=true;

CREATE SECRET "r2_${bucketName}" (
    TYPE R2,
    ACCOUNT_ID '${accountId}',
    KEY_ID '${keyId}',
    REGION 'auto',
    SECRET '${secret}',
    SCOPE 'r2://${bucketName}'
);

SELECT * FROM read_json(
    'r2://${bucketName}/**/*.json.gz',
    compression = 'gzip',
    columns = {},
    format = 'newline_delimited',
    hive_partitioning = true
);
```

```
{
    "errorType": "HTTP",
    "errorMessage": "HTTP Error: HTTP GET error on '/${bucketName}/?encoding-type=url&list-type=2&prefix=' (HTTP 400)",
    "code": "DUCKDB_NODEJS_ERROR",
    "errno": -1,
    "stack": [
        "Error: HTTP Error: HTTP GET error on '/${bucketName}/?encoding-type=url&list-type=2&prefix=' (HTTP 400)"
    ]
}
```

---

Notes:
- The scoped secret is being used, changing config changes the error
- I've tried using a `TYPE 'S3'` secret and hardcoding the endpoint + switching to `s3://*`
- I've tried loading the httpfs extension from `http://extensions.quacking.cloud/` (& the default)
- I've tried to diff the source, but my cpp is ~ toddler level

**Comment by tobilg** [comment]
To me it seems like the JS string template values aren’t replaced. In the code you‘re showing single hyphens… Can you check?

**Comment by qw-in** [comment]
@tobilg sorry I cut it down for the example and made it confusing!

I do interpolate for the secret (see https://github.com/duckdb/duckdb/issues/13459), but it does all work locally & look correct if printed

Currently testing if lambda setting `AWS_SESSION_TOKEN` env vars etc could have any affect (see https://github.com/duckdb/duckdb/blob/8aca4330ac46be3950c6b12e29040322dd245b7a/extension/httpfs/include/s3fs.hpp#L37)

**Comment by qw-in** [comment]
Yep, that did it. Finally!

Some issue with inheritance of the env vars, this fixes it:

```ts
process.env.AWS_REGION = '';
process.env.AWS_DEFAULT_REGION = '';
process.env.AWS_ACCESS_KEY_ID = '';
process.env.AWS_SECRET_ACCESS_KEY = '';
process.env.AWS_SESSION_TOKEN = '';
```

I'll close and open an issue on the main repo

**Comment by qw-in** [comment]
Yeah, seems as though the lambda environment vars being set changes how my `R2` secret behaves. Trying to cut it down for a bug report :)

**Comment by tobilg** [comment]
Those variables are always set via the Lambda runtime, see

https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime

**Comment by qw-in** [comment]
Yeah, the new secret cascade feature in 1.1.0 means that the runtime `AWS_SESSION_TOKEN` gets passed through to the R2 calls, and that causes the `400`. Opened this https://github.com/duckdb/duckdb/issues/14201, thanks for your help!

This seems to work:

```diff

CREATE SECRET "r2_${bucketName}" (
    TYPE R2,
    ACCOUNT_ID '${accountId}',
    KEY_ID '${keyId}',
    REGION 'auto',
    SECRET '${secret}',
    SCOPE 'r2://${bucketName}',
+   SESSION_TOKEN '', 
);
