### ISSUE TITLE
Layer For ARM

### ISSUE THREAD

**Issue by jacob-kleidman** [tobilg/duckdb-nodejs-layer#2]
How hard would it be to build and publish these layers for ARM Lambdas as well?

**Comment by tobilg** [comment]
Should be possible with a second build process. Will look into it.

**Comment by jacob-kleidman** [comment]
Thank you!! Your blog post and shared layer are incredibly helpful

**Comment by tobilg** [comment]
Closed via https://github.com/tobilg/duckdb-nodejs-layer/commit/6a5aba6ed645136a19d8ec6daa3ee72a9c561885
