### ISSUE TITLE
When i use the latest layer with lambda function attached to VPC, it does not work anymore. The same setup worked fine for v0.9.1

### ISSUE THREAD

**Issue by VivekJaganath** [tobilg/duckdb-nodejs-layer#8]

**Comment by tobilg** [comment]
Can you please describe what exactly doesn’t work? Thanks!

**Comment by VivekJaganath** [comment]
For example, if you were to update the 'serverless duckdb' repository's serverless.yaml file with configurations for VPC, EFS, and S3, ensuring correct permissions are set, and then deploy it, the API will respond with a timeout error.

**Comment by tobilg** [comment]
Well, I doubt that the problem lies with this layer, as I run this myself with serverless-duckdb and it works. 

I‘ll close the issue. Feel free to open a new issue in the serverless-duckdb repo if the default configuration serverless.yml deployment doesn’t work.
